## Introduction to OOP in python

#### One of the popular approach to solve a programming problem by creating an objects. this is called as Object Oriented Programming.
  An object has two characteristics :
        1.attributes(name,age,color)
        2. behaviour(learn,study,etc)
In python, the concept OOP follow these things : 1.Inheritance
    2.Encapsulation
    3.Polymorphism
#### Class:
A class is blueprint for the object or Logical entity
#### Object:
Blue print of Class or Instance  of physial entity
#### Methods:
part of class and can be called with object
#### Constructors:

#### class ClassName:
   # some functions and variables
   # function -- used to perform the specific activity
   # variables-- Data(Memory)
#### Functions:
  

In [11]:
def test():
    return
test()

In [15]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [16]:
def test():
    print('test() for function')
    return
test()

test() for function


In [24]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
        
p1=Demo1()
p1.fact(5)

120

In [27]:
class Demo2:
    a=0,b=0
    def Accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("p1= ",p1)
        print("p2= ",p2)
c1= Demo2()
c1.accept(10,20)
c1.display()

SyntaxError: can't assign to literal (<ipython-input-27-f6f5771ba363>, line 2)

In [30]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1 = p1
        self.p2 = p2
    def add(self,p1,p2):
        return p1+p2
c1= Demo2(10,20)
print(c1.add(100,200))

300


In [34]:
class Person():
    #Constructor
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False

#Derived Class
class Employee(Person):
    def isEmployee(self):
        return True  
emp=Person("Pooja")
print(emp.getName(),emp.isEmployee())
emp1=Employee("Swk")
print(emp1.getName(),emp1.isEmployee())

Pooja False
Swk True


In [35]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [36]:
lst =[1,2,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [37]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [38]:
lst =[1.0,2.5,3.6,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [39]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [41]:
#Reshape the given array
#numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
# Append some data --Horizontally
# Append some data --Vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [45]:
# Append some data --Vertical
#vstack(array1,array2)---will be automatically arranged in vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [46]:
#Generate random number from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.07934116 4.63846824 5.47658537 5.44964746 5.52365011 5.36369532
 5.09715834 4.75981763 5.05712752 5.45035324]


In [47]:
# numpy.zeros() and numpy.one()
# Generate an array with all zeros-- numpy.zeros()
# numpy.zeros(shape,dtype=float-,order='C')
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [50]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [51]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [52]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [53]:
np.zeros((4,3),dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [54]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1  1]]


In [3]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [5]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [6]:
#Indexing and slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print("first row",a1[0])

first row [1 2 3]


In [7]:
a1=np.array([(1,2,3),(47,5,6)])
print("second row",a1[1])

second row [47  5  6]


In [9]:
a1=np.array([(1,2,3),(47,5,6)])
print("slicing row",a1[:1])

slicing row [[1 2 3]]


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column",a1[:,2])

slicing last column [3 6]


In [12]:
a1=np.array([(1,2,3),(47,5,6)])
print("row and column",a1[1:,1])

row and column [5]


In [14]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[3.30240429 6.06679143 5.3694694  3.96713243 3.9909167  5.67277381
 4.6660562  4.83027037 3.90291014 3.98388787]
Min value= 3.3024042905620643
Max value= 6.066791431990743
Mean value= 4.575261263861335
Median value= 4.328486451198354


In [15]:
#Multiply  of 1D arrays
#numpy.dot(x,y)--

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [17]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

#### pandas basics:
##### pandas data frames
##### Data analysis with python

In [1]:
import pandas as pd
dict={"name":["anil","akhil","dinesh","harsha","ajay","kranth"],"emailid":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"mobile":[999,222,456,485,258,265]}
b=pd.DataFrame(dict)
print(b)


     name           emailid  mobile
0    anil    anil@gmail.com     999
1   akhil   akhil@gmail.com     222
2  dinesh  dinesh@gmail.com     456
3  harsha  harsha@gmail.com     485
4    ajay    ajay@gmail.com     258
5  kranth  kranth@gmail.com     265


In [2]:
import calendar
c1=calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     